services:
  # client:
  #   build: ./src/client/
  #   ports:
  #     - "8000:8000"
  server:
    build: ./src/server/
    depends_on:
      - db
    ports:
      - "5001:5001"
  db:
    build: ./src/db/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'iccsroot'
      MYSQL_DATABASE: 'tutord'
    volumes:
      - data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  data: